### model
# model_name_or_path: /data/models/huggingface/meta-llama/Meta-Llama-3-70B-Instruct/
model_name_or_path: /data/models/huggingface/meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid # [sigmoid (dpo), orpo, simpo]
# deepspeed: /home/jiaruil5/personality/llm_personality/LLaMA-Factory/examples/deepspeed/ds_z3_offload_config.json
# deepspeed: /home/jiaruil5/personality/llm_personality/LLaMA-Factory/examples/deepspeed/ds_z3_config.json

### dataset
dataset: train_dpo
dataset_dir: /data/user_data/wenkail/llm_personality/align/data_dpo/
template: llama3
# cutoff_len: 2048
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16
# max_samples: 1000
max_new_tokens: 1024
# tokenized_path: /home/jiaruil5/personality/llm_personality/llm_bigfive/align_dpo/tokenized_data/

### output
# TODO: Change Output Dir
output_dir: /data/user_data/wenkail/llm_personality/align/8b_lora_dpo_1e-5
logging_steps: 10
save_steps: 300
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 20
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 300
save_total_limit: 3
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false

report_to: wandb
run_name: train_align_dpo_1e-5_llama3_8b

# CUDA_VISIBLE_DEVICES=0,1,2,3,4 WANDB_PROJECT=llm_personality WANDB_ENTITY=kyle_organization llamafactory-cli train 8b_lora_dpo_1e-5.yaml

# https://github.com/hiyouga/LLaMA-Factory/issues/3880


# CUDA_VISIBLE_DEVICES=0 WANDB_PROJECT=llm_personality WANDB_ENTITY=kyle_organization llamafactory-cli train 8b_lora_dpo_1e-5.yaml