### model
model_name_or_path: /data/models/huggingface/meta-llama/Meta-Llama-3-70B-Instruct/
# model_name_or_path: /compute/babel-9-3/wenkail/.cache/models--TechxGenus--Meta-Llama-3-70B-Instruct-GPTQ/snapshots/e147aa8799dd05d5077f60c79be0d972b002b3ac
# model_name_or_path: /data/models/huggingface/meta-llama/Meta-Llama-3-8B-Instruct/

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: triple  # [sigmoid (dpo), orpo, simpo]
# deepspeed: examples/deepspeed/ds_z3_offload_config.json
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: train_dpo
dataset_dir: /data/user_data/wenkail/llm_personality/align/data_dpo/
template: llama3
# cutoff_len: 2048
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16
# max_samples: 1000
max_new_tokens: 1024
tokenized_path: /compute/babel-9-3/wenkail/llm_personality/generator/llama_3_70b/tokenized_data

### output
output_dir: /compute/babel-9-3/wenkail/llm_personality/generator/llama_3_70b/lora_dpo_1e-5
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 20
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 3
eval_strategy: steps
eval_steps: 1000
save_total_limit: 2
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false

report_to: wandb
run_name: train_align_dpo_llama3_70b_1e-5


# save to /compute/babel-5-23

# 1e-6 
# 1e-5 
# 1e-4 


# 3e-5 
# 3e-6 
# 3e-4
