### model
model_name_or_path: /data/models/huggingface/meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /home/wenkail/llm_personality/LLaMA-Factory/examples/deepspeed/ds_z3_config.json

### dataset
dataset: train_a
dataset_dir: /data/user_data/wenkail/llm_personality/generator/data/
template: llama3
# cutoff_len: 2048
cutoff_len: 512
tokenized_path: /compute/babel-9-3/wenkail/llm_personality/generator/llama_3_8b/tokenized_data_a/
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### generate
max_new_tokens: 512

### output
output_dir: /compute/babel-9-3/wenkail/llm_personality/full_finetune_generator/generator_whole_a_1e-6
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-6
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_steps: 20
bf16: true
ddp_timeout: 180000000
optim: paged_adamw_8bit

### eval
val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000
load_best_model_at_end: true
save_total_limit: 2
metric_for_best_model: eval_loss
greater_is_better: false

## wandb
report_to: wandb
run_name: train_generator_a_1e-6
# CUDA_VISIBLE_DEVICES=0,1,2,3 WANDB_PROJECT=llm_personality WANDB_ENTITY=kyle_organization llamafactory-cli train generator_a_1e-6.yaml