### model
model_name_or_path: /data/user_data/jiaruil5/.cache/models--meta-llama--Meta-Llama-3-8B-Instruct/snapshots/c4a54320a52ed5f88b7a2f84496903ea4ff07b45/

# 1e-6 3e-6 1e-5 3e-5 1e-4 3e-4



### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
# deepspeed: examples/deepspeed/ds_z3_offload_config.json
deepspeed: /home/jiaruil5/personality/llm_personality/LLaMA-Factory/examples/deepspeed/ds_z3_config.json

### dataset
dataset: alpaca_big_five_dataset_train_5_tokens_deduplicated
dataset_dir: /data/user_data/wenkail/llm_personality/generator/data/
template: llama3
# cutoff_len: 2048
cutoff_len: 512
overwrite_cache: true
preprocessing_num_workers: 16
# max_samples: 1000
max_new_tokens: 512

### output
output_dir: /compute/babel-0-37/jiaruil5/personality/checkpoints/generator_lora_1e-6
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 20
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 1000
save_total_limit: 2
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false

report_to: wandb
run_name: train_generator_lora_1e-6

# CUDA_VISIBLE_DEVICES=0 WANDB_PROJECT=llm_personality WANDB_ENTITY=kyle_organization llamafactory-cli train llama3_lora_generator_1e-5.yaml