### model
model_name_or_path: /data/user_data/jiaruil5/.cache/models--meta-llama--Meta-Llama-3-8B-Instruct/snapshots/c4a54320a52ed5f88b7a2f84496903ea4ff07b45/

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /home/jiaruil5/personality/llm_personality/LLaMA-Factory/examples/deepspeed/ds_z3_config.json

### dataset
dataset: alpaca_big_five_dataset_train_5_tokens
dataset_dir: /data/user_data/wenkail/llm_personality/generator/data/
template: llama3
cutoff_len: 2048
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
# output_dir: /data/user_data/wenkail/llm_personality/generator/checkpoints/word5_lr1e-4/
output_dir: /scratch/jiaruil5/personality/checkpoints/word5_lr1e-5
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_steps: 20
fp16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 1000
load_best_model_at_end: true
save_total_limit: 2
metric_for_best_model: eval_loss
greater_is_better: false

## wandb
report_to: wandb
run_name: overfit_generator
# CUDA_VISIBLE_DEVICES=0,1,2,3 WANDB_PROJECT=llm_personality WANDB_ENTITY=kyle_organization llamafactory-cli train llama3_full_sft_psychgen_5_tokens.yaml